language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements-dev.txt
  - pip install pre-commit

script:
  # black (the formatter) is one of our pre-commit hooks, but it requires at least Python 3.6. Separate invocations
  # of pre-commit for each hook *except* black is our way of excluding black in CI in order to allow us to keep
  # building on 3.4/3.5.
  - pre-commit run -a --show-diff-on-failure mypy
  - pre-commit run -a --show-diff-on-failure flake8
  - pre-commit run -a --show-diff-on-failure pyupgrade
  - pre-commit run -a --show-diff-on-failure reorder-python-imports
  - pre-commit run -a --show-diff-on-failure check-docstring-first
  - pre-commit run -a --show-diff-on-failure check-merge-conflict
  - pre-commit run -a --show-diff-on-failure check-vcs-permalinks
  - pre-commit run -a --show-diff-on-failure check-yaml
  - pre-commit run -a --show-diff-on-failure debug-statements
  - pre-commit run -a --show-diff-on-failure end-of-file-fixer
  - pre-commit run -a --show-diff-on-failure trailing-whitespace
  - scripts/tests.sh
  - scripts/docs.sh
