language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements-dev.txt
  - pip install pre-commit

script:
  - pre-commit run -a --show-diff-on-failure
  - scripts/tests.sh
  - scripts/docs.sh
