language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  # TOOD: I feel there's a better way than poking at PYTHONPATH here.
  - flake8
  - PYTHONPATH=. mypy $(find hashdial tests -name '*.py')
  - PYTHONPATH=. pytest
  - cd docs && PYTHONPATH=.. make html
